name: kerja_serabutan
description: Platform kerja lepas untuk pekerjaan serabutan di Indonesia.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.0
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  timeago: ^3.6.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
